---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: source/_posts/spark
  label: Spark
  create: documents
  match: "**/*.md"
- type: directory
  path: source/_posts/fe
  label: 前端
  create: documents
  match: "**/*.md"
- type: directory
  path: source/_posts/life
  label: 生活
  create: documents
  match: "**/*.md"
- type: directory
  path: source/_posts/other
  label: 其他
  create: documents
  match: "**/*.md"
upload_dir: public/images
public_path: https://sparkling-land-blog.s3.ap-east-1.amazonaws.com/public/images
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
